#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nocaselist
Version  : 1.0.3
Release  : 5
URL      : https://files.pythonhosted.org/packages/bb/b1/1bd5eba96cf017ab892390292ee866dcaf77da0bf8058d9c6fe5af520d83/nocaselist-1.0.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/bb/b1/1bd5eba96cf017ab892390292ee866dcaf77da0bf8058d9c6fe5af520d83/nocaselist-1.0.3.tar.gz
Summary  : A case-insensitive list for Python
Group    : Development/Tools
License  : Apache-2.0
Requires: nocaselist-license = %{version}-%{release}
Requires: nocaselist-python = %{version}-%{release}
Requires: nocaselist-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
===============================================

%package license
Summary: license components for the nocaselist package.
Group: Default

%description license
license components for the nocaselist package.


%package python
Summary: python components for the nocaselist package.
Group: Default
Requires: nocaselist-python3 = %{version}-%{release}

%description python
python components for the nocaselist package.


%package python3
Summary: python3 components for the nocaselist package.
Group: Default
Requires: python3-core
Provides: pypi(nocaselist)

%description python3
python3 components for the nocaselist package.


%prep
%setup -q -n nocaselist-1.0.3
cd %{_builddir}/nocaselist-1.0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1602000381
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nocaselist
cp %{_builddir}/nocaselist-1.0.3/LICENSE %{buildroot}/usr/share/package-licenses/nocaselist/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nocaselist/7df059597099bb7dcf25d2a9aedfaf4465f72d8d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
